import { createHash } from 'node:crypto';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const distDirectory = resolve(projectRoot, 'dist');
const workerPath = resolve(distDirectory, 'sw.js');

async function collectFiles(directory) {
  const entries = await readdir(directory);
  const paths = [];

  for (const entry of entries) {
    const absolutePath = resolve(directory, entry);
    const entryStat = await stat(absolutePath);

    if (entryStat.isDirectory()) {
      paths.push(...(await collectFiles(absolutePath)));
    } else if (absolutePath !== workerPath) {
      paths.push(absolutePath);
    }
  }

  return paths;
}

function toScopedUrl(absolutePath) {
  return `./${relative(distDirectory, absolutePath).split(sep).join('/')}`;
}

const files = (await collectFiles(distDirectory)).sort();
const versionHash = createHash('sha256');

for (const file of files) {
  versionHash.update(toScopedUrl(file));
  versionHash.update(await readFile(file));
}

const cacheVersion = versionHash.digest('hex').slice(0, 16);
const precacheUrls = files.map(toScopedUrl);
const serviceWorker = `/* Generated by scripts/build-pwa.mjs. Do not edit dist/sw.js directly. */
const CACHE_PREFIX = 'speedread-pwa-';
const CACHE_NAME = \`\${CACHE_PREFIX}${cacheVersion}\`;
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};
const APP_SHELL_URL = new URL('./index.html', self.registration.scope).toString();

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) =>
        cache.addAll(
          PRECACHE_URLS.map((path) => new URL(path, self.registration.scope).toString())
        )
      )
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
            .map((key) => caches.delete(key))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);

  if (request.method !== 'GET' || url.origin !== self.location.origin) {
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.put(request, copy)));
          }
          return response;
        })
        .catch(() => caches.match(request).then((cached) => cached || caches.match(APP_SHELL_URL)))
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) {
        return cached;
      }

      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.put(request, copy)));
        }
        return response;
      });
    })
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
`;

await writeFile(workerPath, serviceWorker);

console.log(
  `Generated ${relative(projectRoot, workerPath)} with ${precacheUrls.length} offline assets (${cacheVersion}).`
);
